import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "03-Pangolin/07-API/pangolin-integration-api",
    },
    {
      type: "category",
      label: "Organization",
      items: [
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-site-by-nice-id",
          label: "getOrgByOrgIdSiteByNiceId",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-org-by-org-id-site",
          label: "putOrgByOrgIdSite",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-sites",
          label: "getOrgByOrgIdSites",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-pick-site-defaults",
          label: "getOrgByOrgIdPick-site-defaults",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id",
          label: "getOrgByOrgId",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/delete-org-by-org-id",
          label: "deleteOrgByOrgId",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-org-by-org-id",
          label: "postOrgByOrgId",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-org-by-org-id-role",
          label: "putOrgByOrgIdRole",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-orgs-by-org-id-roles",
          label: "getOrgsByOrgIdRoles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-org",
          label: "putOrg",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-user-user-id-orgs",
          label: "getUser:userIdOrgs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-orgs",
          label: "getOrgs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-org-by-org-id-site-by-site-id-resource",
          label: "putOrgByOrgIdSiteBySiteIdResource",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-resources",
          label: "getOrgByOrgIdResources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-domains",
          label: "getOrgByOrgIdDomains",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/delete-org-by-org-id-user-by-user-id",
          label: "deleteOrgByOrgIdUserByUserId",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-user-by-user-id",
          label: "getOrgByOrgIdUserByUserId",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-users",
          label: "getOrgByOrgIdUsers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-org-by-org-id-create-invite",
          label: "postOrgByOrgIdCreate-invite",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-invitations",
          label: "getOrgByOrgIdInvitations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-org-by-org-id-client",
          label: "putOrgByOrgIdClient",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-clients",
          label: "getOrgByOrgIdClients",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-client-by-client-id",
          label: "getOrgByOrgIdClientByClientId",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-access-tokens",
          label: "getOrgByOrgIdAccess-tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/delete-org-by-org-id-api-key-by-api-key-id",
          label: "deleteOrgByOrgIdApi-keyByApiKeyId",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-api-key-by-api-key-id-actions",
          label: "getOrgByOrgIdApi-keyByApiKeyIdActions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-org-by-org-id-api-key-by-api-key-id-actions",
          label: "postOrgByOrgIdApi-keyByApiKeyIdActions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-api-keys",
          label: "getOrgByOrgIdApi-keys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-org-by-org-id-api-key",
          label: "putOrgByOrgIdApi-key",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Site",
      items: [
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-site-by-nice-id",
          label: "getOrgByOrgIdSiteByNiceId",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-site-by-site-id",
          label: "getSiteBySiteId",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/delete-site-by-site-id",
          label: "deleteSiteBySiteId",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-site-by-site-id",
          label: "postSiteBySiteId",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-org-by-org-id-site",
          label: "putOrgByOrgIdSite",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-sites",
          label: "getOrgByOrgIdSites",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-pick-site-defaults",
          label: "getOrgByOrgIdPick-site-defaults",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-site-by-site-id-resources",
          label: "getSiteBySiteIdResources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-site-by-site-id-pick-client-defaults",
          label: "getSiteBySiteIdPick-client-defaults",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Resource",
      items: [
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-resource-by-resource-id-roles",
          label: "postResourceByResourceIdRoles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-resource-by-resource-id-roles",
          label: "getResourceByResourceIdRoles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-resource-by-resource-id",
          label: "getResourceByResourceId",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/delete-resource-by-resource-id",
          label: "deleteResourceByResourceId",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-resource-by-resource-id",
          label: "postResourceByResourceId",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-org-by-org-id-site-by-site-id-resource",
          label: "putOrgByOrgIdSiteBySiteIdResource",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-site-by-site-id-resources",
          label: "getSiteBySiteIdResources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-resources",
          label: "getOrgByOrgIdResources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-resource-by-resource-id-users",
          label: "postResourceByResourceIdUsers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-resource-by-resource-id-users",
          label: "getResourceByResourceIdUsers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-resource-by-resource-id-password",
          label: "postResourceByResourceIdPassword",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-resource-by-resource-id-pincode",
          label: "postResourceByResourceIdPincode",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-resource-by-resource-id-whitelist",
          label: "postResourceByResourceIdWhitelist",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-resource-by-resource-id-whitelist",
          label: "getResourceByResourceIdWhitelist",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-resource-by-resource-id-transfer",
          label: "postResourceByResourceIdTransfer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-resource-by-resource-id-rule",
          label: "putResourceByResourceIdRule",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/delete-resource-by-resource-id-rule-by-rule-id",
          label: "deleteResourceByResourceIdRuleByRuleId",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-resource-by-resource-id-rule-by-rule-id",
          label: "postResourceByResourceIdRuleByRuleId",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-resource-by-resource-id-rules",
          label: "getResourceByResourceIdRules",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-resource-by-resource-id-target",
          label: "putResourceByResourceIdTarget",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-resource-by-resource-id-targets",
          label: "getResourceByResourceIdTargets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-resource-by-resource-id-access-token",
          label: "postResourceByResourceIdAccess-token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-resource-by-resource-id-access-tokens",
          label: "getResourceByResourceIdAccess-tokens",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Role",
      items: [
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-resource-by-resource-id-roles",
          label: "postResourceByResourceIdRoles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-resource-by-resource-id-roles",
          label: "getResourceByResourceIdRoles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-org-by-org-id-role",
          label: "putOrgByOrgIdRole",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/delete-role-by-role-id",
          label: "deleteRoleByRoleId",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-orgs-by-org-id-roles",
          label: "getOrgsByOrgIdRoles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-role-by-role-id-add-by-user-id",
          label: "postRoleByRoleIdAddByUserId",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "User",
      items: [
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-user-user-id-orgs",
          label: "getUser:userIdOrgs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-resource-by-resource-id-users",
          label: "postResourceByResourceIdUsers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-resource-by-resource-id-users",
          label: "getResourceByResourceIdUsers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/delete-org-by-org-id-user-by-user-id",
          label: "deleteOrgByOrgIdUserByUserId",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-user-by-user-id",
          label: "getOrgByOrgIdUserByUserId",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-users",
          label: "getOrgByOrgIdUsers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-role-by-role-id-add-by-user-id",
          label: "postRoleByRoleIdAddByUserId",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Rule",
      items: [
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-resource-by-resource-id-rule",
          label: "putResourceByResourceIdRule",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/delete-resource-by-resource-id-rule-by-rule-id",
          label: "deleteResourceByResourceIdRuleByRuleId",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-resource-by-resource-id-rule-by-rule-id",
          label: "postResourceByResourceIdRuleByRuleId",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-resource-by-resource-id-rules",
          label: "getResourceByResourceIdRules",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Target",
      items: [
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-target-by-target-id",
          label: "getTargetByTargetId",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/delete-target-by-target-id",
          label: "deleteTargetByTargetId",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-target-by-target-id",
          label: "postTargetByTargetId",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-resource-by-resource-id-target",
          label: "putResourceByResourceIdTarget",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-resource-by-resource-id-targets",
          label: "getResourceByResourceIdTargets",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Invitation",
      items: [
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-invitations",
          label: "getOrgByOrgIdInvitations",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Client",
      items: [
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-site-by-site-id-pick-client-defaults",
          label: "getSiteBySiteIdPick-client-defaults",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-org-by-org-id-client",
          label: "putOrgByOrgIdClient",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/delete-client-by-client-id",
          label: "deleteClientByClientId",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-client-by-client-id",
          label: "postClientByClientId",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-clients",
          label: "getOrgByOrgIdClients",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-client-by-client-id",
          label: "getOrgByOrgIdClientByClientId",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Access Token",
      items: [
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-resource-by-resource-id-access-token",
          label: "postResourceByResourceIdAccess-token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-access-tokens",
          label: "getOrgByOrgIdAccess-tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-resource-by-resource-id-access-tokens",
          label: "getResourceByResourceIdAccess-tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/delete-access-token-by-access-token-id",
          label: "deleteAccess-tokenByAccessTokenId",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Identity Provider",
      items: [
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-idp-oidc",
          label: "putIdpOidc",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-idp-idp-id-oidc",
          label: "postIdp:idpIdOidc",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/delete-idp-by-idp-id",
          label: "deleteIdpByIdpId",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-idp-by-idp-id",
          label: "getIdpByIdpId",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-idp",
          label: "getIdp",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-idp-by-idp-id-org-by-org-id",
          label: "putIdpByIdpIdOrgByOrgId",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/delete-idp-by-idp-id-org-by-org-id",
          label: "deleteIdpByIdpIdOrgByOrgId",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-idp-by-idp-id-org-by-org-id",
          label: "postIdpByIdpIdOrgByOrgId",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-idp-by-idp-id-org",
          label: "getIdpByIdpIdOrg",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "API Key",
      items: [
        {
          type: "doc",
          id: "03-Pangolin/07-API/delete-org-by-org-id-api-key-by-api-key-id",
          label: "deleteOrgByOrgIdApi-keyByApiKeyId",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-api-key-by-api-key-id-actions",
          label: "getOrgByOrgIdApi-keyByApiKeyIdActions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/post-org-by-org-id-api-key-by-api-key-id-actions",
          label: "postOrgByOrgIdApi-keyByApiKeyIdActions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/get-org-by-org-id-api-keys",
          label: "getOrgByOrgIdApi-keys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "03-Pangolin/07-API/put-org-by-org-id-api-key",
          label: "putOrgByOrgIdApi-key",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "UNTAGGED",
      items: [
        {
          type: "doc",
          id: "03-Pangolin/07-API/health-check",
          label: "healthCheck",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
